services:
  sarca:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        VERSION: latest
    volumes:
      - ./runtime/sarca:/sarca:ro
      - ./ui/dist:/ui:ro
      - ./docker/sarca-entrypoint.sh:/sarca-entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/sarca-entrypoint.sh"]
