"""Smoke: upload a real image and video through the live API.

Requires a running Sarca with at least one storage worker (Telegram bot).
Credentials default from env or are read from ./sarca.conf / native install conf.
"""

from __future__ import annotations

import io
import os
import struct
import time
import zlib
from pathlib import Path

import httpx
import pytest

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _load_conf_value(key: str) -> str | None:
    for conf in (
        ROOT / "sarca.conf",
        Path.home() / ".local/share/sarca/sarca.conf",
    ):
        if not conf.is_file():
            continue
        for line in conf.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            if k.strip() == key:
                return v.strip().strip('"').strip("'")
    return None


BASE_URL = os.environ.get("SARCA_BASE_URL", "http://127.0.0.1:8001").rstrip("/")
# Prefer sarca.conf over ambient env (CI/agent shells often export e2e@… credentials).
EMAIL = _load_conf_value("SUPERUSER_EMAIL") or os.environ.get("SUPERUSER_EMAIL")
PASSWORD = _load_conf_value("SUPERUSER_PASS") or os.environ.get("SUPERUSER_PASS")


def _minimal_png(width: int = 8, height: int = 8) -> bytes:
    """Valid tiny RGB PNG without external deps."""

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    raw = b"".join(b"\x00" + (b"\x00\xff\x00" * width) for _ in range(height))
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def _minimal_mp4() -> bytes:
    """Tiny ftyp+mdat stub that is a valid-enough container for upload smoke."""
    # Prefer a real fixture if present (generated by ffmpeg).
    fixture = FIXTURES / "smoke.mp4"
    if fixture.is_file() and fixture.stat().st_size > 32:
        return fixture.read_bytes()
    # Minimal ISO BMFF: ftyp + free + mdat with a few bytes
    ftyp = b"isom" + struct.pack(">I", 0) + b"isomiso2mp41"
    ftyp_box = struct.pack(">I", 8 + len(ftyp)) + b"ftyp" + ftyp
    mdat_payload = b"\x00" * 64
    mdat_box = struct.pack(">I", 8 + len(mdat_payload)) + b"mdat" + mdat_payload
    return ftyp_box + mdat_box


@pytest.fixture(scope="module")
def client() -> httpx.Client:
    assert EMAIL and PASSWORD, "SUPERUSER_EMAIL/PASS missing (env or sarca.conf)"
    deadline = time.time() + 60
    last = None
    while time.time() < deadline:
        try:
            r = httpx.post(
                f"{BASE_URL}/api/auth/login",
                json={"email": "probe@example.com", "password": "x"},
                timeout=2.0,
            )
            if r.status_code in (200, 401, 403, 422):
                break
        except Exception as e:  # noqa: BLE001
            last = e
        time.sleep(1)
    else:
        raise RuntimeError(f"API not ready at {BASE_URL}: {last}")

    with httpx.Client(base_url=BASE_URL, timeout=120.0) as c:
        yield c


@pytest.fixture(scope="module")
def auth_headers(client: httpx.Client) -> dict[str, str]:
    r = client.post("/api/auth/login", json={"email": EMAIL, "password": PASSWORD})
    assert r.status_code == 200, r.text
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


@pytest.fixture(scope="module")
def storage_id(client: httpx.Client, auth_headers: dict[str, str]) -> str:
    r = client.get("/api/storages", headers=auth_headers)
    assert r.status_code == 200, r.text
    storages = r.json().get("storages", r.json())
    assert storages, "no storages — bootstrap TELEGRAM_* / STORAGE_NAME or create one in UI"
    # Prefer storage with workers
    workers = client.get("/api/storage_workers", headers=auth_headers)
    assert workers.status_code == 200, workers.text
    wlist = workers.json()
    assert wlist, "no storage workers — attach a Telegram bot before upload smoke"
    sid = wlist[0]["storage_id"]
    assert any(s["id"] == sid for s in storages)
    return sid


def _upload(
    client: httpx.Client,
    headers: dict[str, str],
    storage_id: str,
    filename: str,
    content: bytes,
    content_type: str,
    parent: str = "",
) -> None:
    files = {"file": (filename, io.BytesIO(content), content_type)}
    data = {"path": parent}
    r = client.post(
        f"/api/storages/{storage_id}/files/upload",
        headers=headers,
        files=files,
        data=data,
    )
    assert r.status_code == 201, f"upload {filename} failed: {r.status_code} {r.text}"


def _tree_names(
    client: httpx.Client, headers: dict[str, str], storage_id: str, path: str = ""
) -> dict[str, bool]:
    suffix = path.strip("/")
    url = f"/api/storages/{storage_id}/files/tree/{suffix}" if suffix else f"/api/storages/{storage_id}/files/tree"
    # API path is /*path under files — tree is GET .../files/tree or .../files/tree/{path}
    r = client.get(url, headers=headers)
    if r.status_code == 404:
        r = client.get(f"/api/storages/{storage_id}/files/tree/", headers=headers)
    assert r.status_code == 200, r.text
    items = r.json()
    if isinstance(items, dict):
        items = items.get("files") or items.get("fs") or items.get("items") or []
    return {i["name"]: bool(i.get("is_file", True)) for i in items}


def test_ui_serves_new_bundle(client: httpx.Client) -> None:
    r = client.get("/")
    assert r.status_code == 200
    html = r.text
    assert "index-" in html or "/assets/" in html
    # hashed css from current vite build should be referenced
    assert ".css" in html
    # theme toggle / file icons live in the JS bundle — fetch first asset script
    import re

    m = re.search(r'/assets/(index-[^"]+\.js)', html)
    assert m, html[:500]
    js = client.get(f"/assets/{m.group(1)}")
    assert js.status_code == 200
    body = js.text
    assert "file-type-icon" in body or "FileTypeIcon" in body or "toggleThemeMode" in body or "data-theme" in body


def test_upload_image_and_video_smoke(
    client: httpx.Client, auth_headers: dict[str, str], storage_id: str
) -> None:
    png = (FIXTURES / "smoke.png").read_bytes() if (FIXTURES / "smoke.png").is_file() else _minimal_png()
    mp4 = (FIXTURES / "smoke.mp4").read_bytes() if (FIXTURES / "smoke.mp4").is_file() else _minimal_mp4()
    stamp = str(int(time.time()))
    img_name = f"smoke-{stamp}.png"
    vid_name = f"smoke-{stamp}.mp4"

    _upload(client, auth_headers, storage_id, img_name, png, "image/png")
    _upload(client, auth_headers, storage_id, vid_name, mp4, "video/mp4")

    # Trailing slash on parent must still produce a file path (not a folder marker).
    nested = f"nested-{stamp}.png"
    _upload(
        client,
        auth_headers,
        storage_id,
        nested,
        png,
        "image/png",
        parent="smoke-dir/",
    )

    r = client.get(f"/api/storages/{storage_id}/files/tree/", headers=auth_headers)
    assert r.status_code == 200, r.text
    names = {e["name"]: e["is_file"] for e in r.json()}
    assert names.get(img_name) is True, names
    assert names.get(vid_name) is True, names
    assert names.get("smoke-dir") is False, names

    r = client.get(
        f"/api/storages/{storage_id}/files/tree/smoke-dir", headers=auth_headers
    )
    assert r.status_code == 200, r.text
    nested_names = {e["name"]: e["is_file"] for e in r.json()}
    assert nested_names.get(nested) is True, nested_names
